project_id = "orbygspxutudncbyipst"

[functions.fetch-auctions]
verify_jwt = false

[functions.sync-auctions]
verify_jwt = false

[functions.cron-sync-auctions]
verify_jwt = false

[functions.check-pattern-alerts]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false
